#!/usr/bin/python3



def validUTF8(data):
    result = False
    for i in len(data):
        num = str(bin(data[i])[2:])
        if len(num) <= 8:
            result = True
        else:
            result = False
            break 
    return (result)       
